# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qcli < Formula
  desc "CLI tool written in Go, designed to streamline integrations from the terminal."
  homepage "https://github.com/quinn-collins/qcli"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Darwin_x86_64.tar.gz"
      sha256 "e3067d0fc1cf0f0f3eed1eb454c833971dbff9c1aa4b9396ad541ec354021b80"

      def install
        bin.install "qcli"
      end
    end
    on_arm do
      url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Darwin_arm64.tar.gz"
      sha256 "d27757bf163d310bc20d790462420381bd62d876f77492e738dfc88a86585ff2"

      def install
        bin.install "qcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Linux_x86_64.tar.gz"
        sha256 "16ef86f228c6ef799146127a93863f882d56539b86bed31a1a35c8e7be8ab060"

        def install
          bin.install "qcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Linux_arm64.tar.gz"
        sha256 "9138a5debf98bf6f0af660cb41418f45fec260fcbcf26a0ac0653c6a7077c31d"

        def install
          bin.install "qcli"
        end
      end
    end
  end
end
