# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qcli < Formula
  desc "CLI tool written in Go, designed to streamline integrations from the terminal."
  homepage "https://github.com/quinn-collins/qcli"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Darwin_x86_64.tar.gz"
      sha256 "f37cad22ac2d56a34c890b7f6307e50414d037d8fbcf9ec2e9fe0357ef872daa"

      def install
        bin.install "qcli"
      end
    end
    on_arm do
      url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Darwin_arm64.tar.gz"
      sha256 "3f4db59355609827370b47bf3663c97d7b05288b2a798ef1fffad03fa1908b2a"

      def install
        bin.install "qcli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Linux_x86_64.tar.gz"
        sha256 "2ae068d1c27ea25109b3b776e7a221555c7c21b9bc389ff3532f558d0eacc202"

        def install
          bin.install "qcli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn-collins/qcli/releases/download/v0.1.1/qcli_Linux_arm64.tar.gz"
        sha256 "a8b98fc4a68c6f0312a598ac7c6fb6c1cbc430f875032d52300a2785c9cea1cb"

        def install
          bin.install "qcli"
        end
      end
    end
  end
end
